language: node_js
node_js:
- '10.10'
deploy:
  provider: heroku
  app: shaunbot1
  api_key:
    secure: 1L4gALg3RNXq7zDAIzrUKjek6WZd2ixLsIn4D7xIjLb9uo2rqLbjWIsJeMhQEYBK7M16Jdoh6iJbk7VWNtEEynFe+fHiTYv0zAPsPDRhWnrWr7v8TiUvacoRs4ZV0EKvhsgVRpo6041TbmZdbbIpMgNWw8kcLwLeYELSeRIoxrVPHRsS11BYpSDdQXhSm8CuyHSap/oYr0LxHLrrUKfOC5wfhutNR/7XBjLbUKbf+WXfuqDpR72Dm0GEZncL+tv3s0sU45DpG87F3etrUV8TNKSEyEesRUT2rIVpQAvYNWrJ38J+2bn1O0hdy2NwnIKORr72UPq8Mwgb6eqMJ7oy41hHqJ0+B6HsbajbI7plYhy3zHSRZ++l7RrEB6M8j/fA10XiXrPxqNN10dcDOhLJR3Skw6YV0EBRptfts0X3pWmPZh46zfyYgIKOHqyP7NmBdRXYr5nQpfGUZ6earz6rAxMz6qln7lhyHnUbq4S/V5Yq+iZKq5eTWHbwhrnFpMOPTGQdAE3Iu32Hy0YATMgBNNyKlo1F01oPm/6QMTizyLAOqkgNnXMoZwXbe4QdR61NF5Na5eO9EW9U6R4WT7Zve27/l+j0MYwTZoUdoeb2Vig6U3fW6pDMSnGiYnmzkZ83KVPuKE1V5bDmqMpczYHQtUShlCnmInaOygP6HyUTwSQ=
